"""Scanner registry and tool catalogue.

``REGISTRY`` maps a tool id to its streaming generator. ``TOOLS`` is the
front-end-facing catalogue describing each tool (label, target hint, and any
extra options) so the UI can render itself dynamically.
"""

from . import (
    auth_crawl,
    crawl,
    csrf,
    dirbuster,
    dns_zone_transfer,
    httpx_probe,
    idor,
    injection,
    jwt_audit,
    nmap_scan,
    nuclei_scan,
    origin_discovery,
    reverseip,
    ssrf,
    subdomain,
    takeover,
    techdetect,
    waf_test,
    webaudit,
    whois_lookup,
)

REGISTRY = {
    "subdomains": subdomain.stream,
    "nmap": nmap_scan.stream,
    "httpx": httpx_probe.stream,
    "nuclei": nuclei_scan.stream,
    "whois": whois_lookup.stream,
    "reverse": reverseip.stream,
    "tech": techdetect.stream,
    "dirbuster": dirbuster.stream,
    "dns_zt": dns_zone_transfer.stream,
    "origin": origin_discovery.stream,
    "crawl": crawl.stream,
    "injection": injection.stream,
    "webaudit": webaudit.stream,
    "waf": waf_test.stream,
    "auth_crawl": auth_crawl.stream,
    "takeover": takeover.stream,
    "ssrf": ssrf.stream,
    "idor": idor.stream,
    "jwt": jwt_audit.stream,
    "csrf": csrf.stream,
}

TOOLS = [
    {
        "id": "subdomains",
        "name": "Subdomain Enum",
        "description": "Discover subdomains with subfinder",
        "icon": "globe",
        "target_label": "Domain",
        "placeholder": "example.com",
    },
    {
        "id": "nmap",
        "name": "Port Scan",
        "description": "Map open ports & services with nmap",
        "icon": "radar",
        "target_label": "Host / IP",
        "placeholder": "scanme.nmap.org",
        "options": [
            {
                "key": "scan_type",
                "label": "Scan profile",
                "default": "quick",
                "choices": [
                    {"value": "quick", "label": "Quick (top ports)"},
                    {"value": "service", "label": "Service / version"},
                    {"value": "full", "label": "Full (all ports)"},
                    {"value": "aggressive", "label": "Aggressive (-A)"},
                    {"value": "os", "label": "OS detection"},
                    {"value": "udp", "label": "UDP top 20"},
                ],
            }
        ],
    },
    {
        "id": "httpx",
        "name": "HTTP Probe",
        "description": "Find live hosts & fingerprint them (httpx)",
        "icon": "pulse",
        "target_label": "Host(s) / URL(s)",
        "placeholder": "example.com, sub.example.com",
    },
    {
        "id": "nuclei",
        "name": "Vuln Scan",
        "description": "CVE / misconfig detection (nuclei)",
        "icon": "bug",
        "target_label": "Target(s)",
        "placeholder": "https://example.com",
        "options": [
            {
                "key": "severity",
                "label": "Min severity",
                "default": "low,medium,high,critical",
                "choices": [
                    {"value": "low,medium,high,critical", "label": "Low → Critical"},
                    {"value": "medium,high,critical", "label": "Medium → Critical"},
                    {"value": "high,critical", "label": "High & Critical"},
                    {"value": "critical", "label": "Critical only"},
                    {"value": "all", "label": "Everything (incl. info)"},
                ],
            }
        ],
    },
    {
        "id": "dirbuster",
        "name": "Content Discovery",
        "description": "Brute-force paths with ffuf",
        "icon": "folder",
        "target_label": "URL",
        "placeholder": "https://example.com",
    },
    {
        "id": "tech",
        "name": "Tech Detect",
        "description": "Fingerprint the technology stack",
        "icon": "cpu",
        "target_label": "URL",
        "placeholder": "https://example.com",
    },
    {
        "id": "whois",
        "name": "WHOIS",
        "description": "Registration & ownership records",
        "icon": "id",
        "target_label": "Domain",
        "placeholder": "example.com",
    },
    {
        "id": "reverse",
        "name": "Reverse IP",
        "description": "Find domains sharing an IP",
        "icon": "swap",
        "target_label": "IP / Host",
        "placeholder": "8.8.8.8",
    },
    {
        "id": "dns_zt",
        "name": "DNS Zone Transfer",
        "description": "Attempt AXFR — expose all DNS records",
        "icon": "globe",
        "target_label": "Domain",
        "placeholder": "example.com",
    },
    {
        "id": "origin",
        "name": "Origin Discovery",
        "description": "Find the real server behind a CDN/WAF",
        "icon": "radar",
        "target_label": "Domain",
        "placeholder": "example.com",
    },
    {
        "id": "crawl",
        "name": "Deep Crawl",
        "description": "Crawl + hidden-parameter & JS endpoint discovery",
        "icon": "folderTree",
        "target_label": "URL",
        "placeholder": "https://example.com",
    },
    {
        "id": "injection",
        "name": "Injection Scan",
        "description": "Active SQLi (sqlmap) & XSS (dalfox) testing",
        "icon": "bug",
        "target_label": "URL (with params)",
        "placeholder": "https://example.com/?id=1",
    },
    {
        "id": "webaudit",
        "name": "Web Audit",
        "description": "Headers, CORS, cookies, exposed files, TLS",
        "icon": "shield",
        "target_label": "URL",
        "placeholder": "https://example.com",
    },
    {
        "id": "waf",
        "name": "WAF Test",
        "description": "Measure what the WAF blocks vs. lets through",
        "icon": "shield",
        "target_label": "URL",
        "placeholder": "https://example.com",
    },
    {
        "id": "takeover",
        "name": "Subdomain Takeover",
        "description": "Detect dangling DNS / unclaimed provider resources",
        "icon": "globe",
        "target_label": "Hostname",
        "placeholder": "sub.example.com",
    },
    {
        "id": "ssrf",
        "name": "SSRF Probe",
        "description": "Detect + safely validate server-side request forgery",
        "icon": "radar",
        "target_label": "URL (with params)",
        "placeholder": "https://example.com/fetch?url=x",
    },
    {
        "id": "auth_crawl",
        "name": "Authenticated Crawl",
        "description": "Log in & map the attack surface behind auth",
        "icon": "id",
        "target_label": "URL",
        "placeholder": "https://app.example.com",
        "options": [
            {
                "key": "cookie",
                "label": "Session cookie",
                "type": "text",
                "default": "",
                "placeholder": "session=abc; token=xyz",
            },
            {
                "key": "auth_header",
                "label": "Auth header",
                "type": "text",
                "default": "",
                "placeholder": "Authorization: Bearer …",
            },
        ],
    },
]


def get_scanner(tool_id: str):
    return REGISTRY.get(tool_id)
