"""WAF-effectiveness test (P4) — pure-Python, requests-only.

Measures whether a target's Web Application Firewall blocks common attack
*patterns* so a defender can HARDEN their WAF. This scanner is strictly
**defensive and non-destructive**:

  * It only ever sends ``GET`` requests.
  * The well-known WAF-trigger strings are placed in a single, clearly-labeled,
    benign query parameter (``?redopsx_wafcheck=<test-string>``) that no real
    application reads — nothing is executed, no form is submitted, no
    state-changing/auth endpoint is touched.
  * Every request carries an attributable ``X-RedOpsX-WAF-Test: 1`` header so
    the traffic is obvious in the target's own logs.

The output is a *hardening signal*: for each OWASP category we report whether
the WAF BLOCKED the labeled test string (403/406/429/501 or a challenge /
"access denied" body) or PASSED it through (same behaviour as the baseline).
A category that PASSES is surfaced as an info/low finding recommending the
defender verify their protection — it is NOT an exploit or a vulnerability
claim about the application itself.
"""

import threading
import time
from typing import Iterator, Optional
from urllib.parse import urlencode, urlparse, urlunparse

import requests

from .. import safe_http
from .base import ensure_url, error, log, reject_optionlike, result

# Attributable, benign identity for every probe. Placing the marker in the
# param name AND a header makes the test traffic trivially auditable.
_UA = "Mozilla/5.0 (RedOpsX WAF-Effectiveness Test; +defensive-hardening)"
_MARKER_PARAM = "redopsx_wafcheck"
_HEADERS = {
    "User-Agent": _UA,
    "X-RedOpsX-WAF-Test": "1",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
}
_TIMEOUT = 8.0
_SLEEP = 0.4  # polite rate-limit between probes

# Status codes a WAF typically returns when it blocks a request.
_BLOCK_STATUSES = {403, 406, 429, 501, 999}

# Substrings that commonly appear in a WAF block / challenge / interstitial body.
_BLOCK_BODY_MARKERS = (
    "access denied",
    "request blocked",
    "blocked by",
    "web application firewall",
    "waf",
    "forbidden",
    "not acceptable",
    "attention required",  # Cloudflare
    "cf-error",
    "ray id",
    "just a moment",  # Cloudflare JS challenge
    "checking your browser",
    "incident id",  # Imperva/Incapsula
    "_incapsula_resource",
    "sucuri",
    "you have been blocked",
    "malicious",
    "security check",
    "unusual traffic",
    "captcha",
    "mod_security",
    "modsecurity",
    "this request has been blocked",
    "the requested url was rejected",  # F5 BIG-IP ASM
)

# WAF signatures: (display name, [header-substring...], [cookie-substring...],
# [body-substring...]). Header/cookie checks are case-insensitive substrings.
_WAF_SIGNATURES = [
    ("Cloudflare", ["cf-ray", "cf-cache-status", "cf-mitigated"], ["__cfduid", "__cf_bm", "cf_clearance"], ["attention required", "cloudflare", "cf-ray"]),
    ("Akamai", ["akamai", "x-akamai", "akamaighost"], ["ak_bmsc", "akamai"], ["akamai"]),
    ("Sucuri CloudProxy", ["x-sucuri-id", "x-sucuri-cache", "sucuri"], ["sucuri"], ["sucuri", "access denied - sucuri"]),
    ("Imperva Incapsula", ["x-iinfo", "x-cdn"], ["incap_ses", "visid_incap", "nlbi_"], ["incapsula", "_incapsula_resource", "incident id"]),
    ("AWS WAF / CloudFront", ["x-amz-cf-id", "x-amzn-waf", "x-amzn-requestid"], ["aws-waf-token", "awsalb"], []),
    ("F5 BIG-IP ASM", ["x-waf-event", "x-wa-info"], ["ts", "bigipserver", "f5_cspm"], ["the requested url was rejected"]),
    ("ModSecurity", ["mod_security", "modsecurity"], [], ["mod_security", "modsecurity", "this request has been blocked"]),
    ("Hostinger hCDN", ["x-hcdn", "hcdn"], ["hcdn"], ["hcdn"]),
    ("Barracuda", ["barra_counter_session", "barracuda"], ["barra_counter_session"], ["barracuda"]),
    ("Fastly", ["x-fastly", "fastly"], [], []),
    ("StackPath / MaxCDN", ["x-sp-", "stackpath"], [], []),
    ("Wordfence", ["wordfence"], [], ["wordfence", "generated by wordfence"]),
]

# One small set of well-known WAF-trigger TEST strings per OWASP category.
# These are placed in a benign, non-executed labeled query param only.
_CATEGORY_TESTS = [
    ("SQL Injection", "' OR '1'='1"),
    ("XSS", "<script>alert(1)</script>"),
    ("Path Traversal / LFI", "../../../../etc/passwd"),
    ("OS Command Injection", ";id"),
    ("SSTI", "{{7*7}}"),
]


def _add_marker_param(url: str, value: str) -> str:
    """Return ``url`` with ``?redopsx_wafcheck=<value>`` appended safely.

    The test string only ever lands in this single labeled query parameter,
    urlencoded, so it is transported as inert data — never as a path, header,
    body, or anything an application would act upon.
    """
    parts = urlparse(url)
    query = urlencode({_MARKER_PARAM: value})
    if parts.query:
        query = parts.query + "&" + query
    return urlunparse((parts.scheme, parts.netloc, parts.path, parts.params, query, parts.fragment))


def _detect_waf(response: requests.Response) -> Optional[str]:
    """Return the name of a detected WAF from response signatures, else None."""
    header_blob = " ".join(f"{k}: {v}" for k, v in response.headers.items()).lower()
    server = response.headers.get("Server", "").lower()
    cookie_blob = " ".join(response.cookies.keys()).lower()
    set_cookie = response.headers.get("Set-Cookie", "").lower()
    cookie_blob = (cookie_blob + " " + set_cookie).strip()
    try:
        body = (response.text or "")[:20000].lower()
    except Exception:  # noqa: BLE001 - decoding can rarely raise
        body = ""

    for name, hdr_sigs, cookie_sigs, body_sigs in _WAF_SIGNATURES:
        if any(sig in header_blob or sig in server for sig in hdr_sigs):
            return name
        if cookie_sigs and any(sig in cookie_blob for sig in cookie_sigs):
            return name
        if body_sigs and any(sig in body for sig in body_sigs):
            return name
    return None


def _looks_blocked(response: requests.Response, baseline_status: Optional[int]) -> bool:
    """Heuristic: did the WAF block this probe?

    A probe is "blocked" if it returns a typical block status, or if its body
    carries a challenge / access-denied marker while the baseline did not
    obviously do so.
    """
    if response.status_code in _BLOCK_STATUSES:
        return True
    # A probe that suddenly 4xx/5xx's when the baseline was a 2xx/3xx is a
    # strong block signal (the marker param is inert, so the app itself
    # shouldn't error on it).
    if baseline_status is not None and baseline_status < 400 and response.status_code >= 400:
        return True
    try:
        body = (response.text or "")[:20000].lower()
    except Exception:  # noqa: BLE001
        body = ""
    if any(marker in body for marker in _BLOCK_BODY_MARKERS):
        return True
    return False


def _get(url: str) -> Optional[requests.Response]:
    try:
        return safe_http.safe_request(
            "GET",
            url,
            headers=_HEADERS,
            timeout=_TIMEOUT,
            allow_redirects=True,
        )
    except requests.RequestException:
        return None


def stream(target: str, cancel: Optional[threading.Event] = None, **options) -> Iterator[dict]:
    """Run the WAF-effectiveness test against ``target`` (defensive, GET-only)."""
    try:
        url = ensure_url(target)
        # ensure_url already validates the host; re-assert defensively.
        reject_optionlike(urlparse(url).netloc)
    except ValueError as exc:
        yield error(f"Invalid target: {exc}")
        return
    if not url:
        yield error("A target URL is required.")
        return

    yield log(f"WAF-effectiveness test (defensive / non-destructive) against {url}")
    yield log("All probes are GET-only, labeled with ?redopsx_wafcheck= and the "
              "X-RedOpsX-WAF-Test header. Nothing is executed.")

    # ---- 1. Baseline -------------------------------------------------------
    yield log("Establishing baseline (normal GET) ...")
    baseline = _get(url)
    if baseline is None:
        yield error(f"Baseline request to {url} failed (host unreachable or timed out).")
        # Still return a valid, empty-ish result so callers never crash.
        yield result({
            "target": url,
            "waf_detected": False,
            "waf_name": None,
            "baseline_status": None,
            "categories": [],
            "coverage_pct": 0,
            "findings": [{
                "name": "Target unreachable",
                "severity": "info",
                "category": "connectivity",
                "description": f"Could not reach {url} to run the WAF test.",
            }],
        })
        return

    baseline_status = baseline.status_code
    yield log(f"Baseline status: {baseline_status} {baseline.reason}")

    # ---- 2. Detect a WAF ---------------------------------------------------
    waf_name = _detect_waf(baseline)
    waf_detected = waf_name is not None
    if waf_detected:
        yield log(f"[OK] WAF detected: {waf_name}")
    else:
        yield log("No WAF signature found in baseline response (may still block on attack patterns).")

    if cancel is not None and cancel.is_set():
        yield log("[STOPPED] Cancelled by user.")
        return

    # ---- 3. Category probes ------------------------------------------------
    categories = []
    findings = []
    blocked_count = 0

    for name, payload in _CATEGORY_TESTS:
        if cancel is not None and cancel.is_set():
            yield log("[STOPPED] Cancelled by user.")
            break

        probe_url = _add_marker_param(url, payload)
        yield log(f"Probing {name} test string (benign, labeled param) ...")
        resp = _get(probe_url)

        if resp is None:
            # Treat a dropped connection as an inconclusive/blocked-ish signal
            # (some WAFs RST the connection). Mark not-blocked-conclusively.
            yield log(f"  {name}: no response (connection dropped or timed out) — inconclusive")
            categories.append({
                "name": name,
                "payload": payload,
                "blocked": None,
                "status": None,
            })
            findings.append({
                "name": f"WAF test inconclusive for {name}",
                "severity": "info",
                "category": name,
                "description": (
                    f"The {name} test string produced no response (connection dropped "
                    f"or timed out). Could not determine whether the WAF blocked it — "
                    f"re-run or verify manually."
                ),
            })
            time.sleep(_SLEEP)
            continue

        blocked = _looks_blocked(resp, baseline_status)
        categories.append({
            "name": name,
            "payload": payload,
            "blocked": bool(blocked),
            "status": resp.status_code,
        })

        if blocked:
            blocked_count += 1
            yield log(f"  {name}: BLOCKED (status {resp.status_code}) [OK]")
        else:
            yield log(f"  {name}: PASSED THROUGH (status {resp.status_code}) — hardening signal")
            findings.append({
                "name": f"WAF did not block {name} test",
                "severity": "low" if waf_detected else "info",
                "category": name,
                "payload": payload,
                "status": resp.status_code,
                "description": (
                    f"The {name} WAF-trigger test string passed through to the "
                    f"application (status {resp.status_code}, same class as the "
                    f"baseline {baseline_status}). Verify that protection against "
                    f"{name} is configured on your WAF. This is a hardening signal, "
                    f"not proof of an exploitable vulnerability."
                ),
            })

        time.sleep(_SLEEP)

    # ---- 4. Coverage score -------------------------------------------------
    total = len(_CATEGORY_TESTS)
    coverage_pct = round((blocked_count / total) * 100) if total else 0
    yield log(
        f"[OK] Coverage: {blocked_count}/{total} categories blocked ({coverage_pct}%). "
        f"WAF detected: {waf_detected}"
    )

    # ---- 5. Structured result ---------------------------------------------
    yield result({
        "target": url,
        "waf_detected": waf_detected,
        "waf_name": waf_name,
        "baseline_status": baseline_status,
        "categories": categories,
        "coverage_pct": coverage_pct,
        "findings": findings,
    })
