apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reconx.configMapName" . }}
  labels:
    {{- include "reconx.labels" . | nindent 4 }}
data:
  RECONX_MODE: {{ .Values.env.extra.RECONX_MODE | default "self-hosted" | quote }}
  RECONX_APP_VERSION: {{ .Chart.AppVersion | quote }}
  BACKEND_PORT: {{ .Values.backend.containerPort | quote }}
  {{- if .Values.ingress.enabled }}
  PUBLIC_URL: {{ printf "http%s://%s" (ternary "s" "" .Values.ingress.tls.enabled) .Values.ingress.host | quote }}
  {{- end }}
  {{- range $key, $value := .Values.env.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
